let myLists = JSON.parse(window.localStorage.getItem("Lists.To.Do")) || []
const myListsUl = document.querySelector(".listsWrapper")
const myTasksUl = document.querySelector(".tasksWrapper")
const tasksContainer = document.querySelector("aside.tasksContainer")
const listsForm = document.forms["addListForm"]
const tasksForm = document.forms["addTaskForm"]
const newEntry = listsForm["newEntryInput"]
const newTask = tasksForm["newTaskInput"]
const listName = document.querySelector("h3.listName")
const tasksCounter = document.querySelector(".tasksCounter")
const clearBtn = document.querySelector(".clear")
const delBtn = document.querySelector(".delete")
